In [310]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [311]:
#read datasets with pandas

#Training Data
train_df = pd.read_csv('train.csv')

#Testing Data
test_df = pd.read_csv('test.csv')

In [312]:
#describe the training dataframe
train_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [313]:
#describe the test dataframe
test_df.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [314]:
#show the train dataframe head
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [315]:
#show the test dataframe head
test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [316]:
#define a function that lists the number of missing values for each feature to help clean the data
def features_missing_values(df):
    return df.isnull().sum()

In [317]:
# Check for missing values in all columns of training data
features_missing_values(train_df)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [318]:
# Check for missing values in all columns of test data
features_missing_values(test_df)

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [319]:
#drop passengerId column
train_df = train_df.drop(columns=['PassengerId'])
test_df = test_df.drop(columns=['PassengerId'])

In [320]:
train_df = train_df.drop_duplicates()

In [321]:
import re

#Define title and family name extraction function using regex
def extract_titanic_names(full_name):
    if not isinstance(full_name, str):
        return pd.Series([None, None])
    
    # Regex breakdown for "Last, Title. First":
    # ^(?P<family_name>[^,]+) -> Everything before the comma is the family name
    # ,\s*(?P<title>[^\.]+)\. -> The title is between the comma+space and the dot
    pattern = r'^(?P<family_name>[^,]+),\s*(?P<title>[^\.]+)\.'
    
    match = re.search(pattern, full_name.strip())
    
    if match:
        family_name = match.group('family_name').strip()
        title = match.group('title').strip()
        return pd.Series([family_name, title])
    
    return pd.Series([None, None])

# 3. Apply the function to create new columns
train_df[['Family_Name', 'Title']] = train_df['Name'].apply(extract_titanic_names)
test_df[['Family_Name', 'Title']] = test_df['Name'].apply(extract_titanic_names)

In [322]:
train_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Name,Title
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr

In [323]:
test_df.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Name,Title
0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Kelly,Mr
1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Wilkes,Mrs
2,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Myles,Mr
3,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Wirz,Mr
4,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Hirvonen,Mrs

In [324]:
#drop Name column after extracting title and family_name
train_df = train_df.drop(columns='Name')
test_df = test_df.drop(columns='Name')

In [325]:
#define a function that lists different titles with their frequencies
def list_titles_with_counts(df):
    return df['Title'].value_counts()

In [326]:
list_titles_with_counts(train_df)

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Major             2
Mlle              2
Col               2
Don               1
Mme               1
Ms                1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [327]:
list_titles_with_counts(test_df)

Title
Mr        240
Miss       78
Mrs        72
Master     21
Col         2
Rev         2
Ms          1
Dr          1
Dona        1
Name: count, dtype: int64

In [328]:
#define a function that replaces non-frequent titles with 'rare' to reduce on-hot encoding sparsity
def clean_titles(df):
    # Map rare or french variations to standard equivalents
    title_mapping = {
        'Mlle': 'Miss',
        'Ms': 'Miss',
        'Mme': 'Mrs',
    }
    df['Title'] = df['Title'].replace(title_mapping)
    
    # Group anything else very rare into a single 'Rare' bucket
    rare_titles = ['Dr', 'Rev', 'Major', 'Col', 'Don', 'Lady', 'Sir', 'Capt', 'the Countess', 'Jonkheer']
    df['Title'] = df['Title'].replace(rare_titles, 'Rare')
    
    return df

#replace non-frequent title values with 'Rare'
train_df = clean_titles(train_df)
test_df = clean_titles(test_df)

In [329]:
train_df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Name,Title
0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr
1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss
3,1,1,female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs
4,0,3,male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr

In [330]:
test_df.head()

,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Name,Title
0,3,male,34.5,0,0,330911,7.8292,NaN,Q,Kelly,Mr
1,3,female,47.0,1,0,363272,7.0000,NaN,S,Wilkes,Mrs
2,2,male,62.0,0,0,240276,9.6875,NaN,Q,Myles,Mr
3,3,male,27.0,0,0,315154,8.6625,NaN,S,Wirz,Mr
4,3,female,22.0,1,1,3101298,12.2875,NaN,S,Hirvonen,Mrs

In [331]:
#since sibsp and parch have no missing values , create a family_size feature that's equal to the sum of all related people to a single individual
train_df['Family_Size'] = train_df['Parch'] + train_df['SibSp'] + 1
test_df['Family_Size'] = test_df['Parch'] + test_df['SibSp'] + 1
columns_to_drop = ['Parch' ,'SibSp']
train_df = train_df.drop(columns=columns_to_drop)
test_df = test_df.drop(columns=columns_to_drop)

In [332]:
train_df.head()

,Survived,Pclass,Sex,Age,Ticket,Fare,Cabin,Embarked,Family_Name,Title,Family_Size
0,0,3,male,22.0,A/5 21171,7.2500,NaN,S,Braund,Mr,2
1,1,1,female,38.0,PC 17599,71.2833,C85,C,Cumings,Mrs,2
2,1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss,1
3,1,1,female,35.0,113803,53.1000,C123,S,Futrelle,Mrs,2
4,0,3,male,35.0,373450,8.0500,NaN,S,Allen,Mr,1

In [333]:
test_df.head()

,Pclass,Sex,Age,Ticket,Fare,Cabin,Embarked,Family_Name,Title,Family_Size
0,3,male,34.5,330911,7.8292,NaN,Q,Kelly,Mr,1
1,3,female,47.0,363272,7.0000,NaN,S,Wilkes,Mrs,2
2,2,male,62.0,240276,9.6875,NaN,Q,Myles,Mr,1
3,3,male,27.0,315154,8.6625,NaN,S,Wirz,Mr,1
4,3,female,22.0,3101298,12.2875,NaN,S,Hirvonen,Mrs,3

In [334]:
#Bin the family size feature into 3 categories: Alone , Small , Large
#Training set
conditions = [
    train_df['Family_Size'] == 1,
    train_df['Family_Size'].between(2, 4)
]
choices = ['Alone', 'Small']

train_df['Family_Category'] = np.select(conditions, choices, default='Large')

train_df

,Survived,Pclass,Sex,Age,Ticket,Fare,Cabin,Embarked,Family_Name,Title,Family_Size,Family_Category
0,0,3,male,22.0,A/5 21171,7.2500,NaN,S,Braund,Mr,2,Small
1,1,1,female,38.0,PC 17599,71.2833,C85,C,Cumings,Mrs,2,Small
2,1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss,1,Alone
3,1,1,female,35.0,113803,53.1000,C123,S,Futrelle,Mrs,2,Small
4,0,3,male,35.0,373450,8.0500,NaN,S,Allen,Mr,1,Alone
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,211536,13.0000,NaN,S,Montvila,Rare,1,Alone
887,1,1,female,19.0,112053,30.0000,B42,S,Graham,Miss,1,Alone
888,0,3,female,NaN,W./C. 6607,23.4500,NaN,S,Johnston,Miss,4,Small
889,1,1,male,26.0,111369,30.0000,C148,C,Behr,Mr,1,Alone
890,0,3,male,32.0,370376,7.7500,NaN,Q,Dooley,Mr,1,Alone

In [335]:
#Bin the family size feature into 3 categories: Alone , Small , Large
#Test Set
conditions = [
    test_df['Family_Size'] == 1,
    test_df['Family_Size'].between(2, 4)
]
choices = ['Alone', 'Small']

test_df['Family_Category'] = np.select(conditions, choices, default='Large')

test_df

,Pclass,Sex,Age,Ticket,Fare,Cabin,Embarked,Family_Name,Title,Family_Size,Family_Category
0,3,male,34.5,330911,7.8292,NaN,Q,Kelly,Mr,1,Alone
1,3,female,47.0,363272,7.0000,NaN,S,Wilkes,Mrs,2,Small
2,2,male,62.0,240276,9.6875,NaN,Q,Myles,Mr,1,Alone
3,3,male,27.0,315154,8.6625,NaN,S,Wirz,Mr,1,Alone
4,3,female,22.0,3101298,12.2875,NaN,S,Hirvonen,Mrs,3,Small
...,...,...,...,...,...,...,...,...,...,...,...
413,3,male,NaN,A.5. 3236,8.0500,NaN,S,Spector,Mr,1,Alone
414,1,female,39.0,PC 17758,108.9000,C105,C,Oliva y Ocana,Dona,1,Alone
415,3,male,38.5,SOTON/O.Q. 3101262,7.2500,NaN,S,Saether,Mr,1,Alone
416,3,male,NaN,359309,8.0500,NaN,S,Ware,Mr,1,Alone
417,3,male,NaN,2668,22.3583,NaN,C,Peter,Master,3,Small

In [336]:
#Extract Letters from cabin numbers:
# 1. Fill missing cabins with 'U' for Unknown
train_df['Cabin'] = train_df['Cabin'].fillna('U')
test_df['Cabin'] = test_df['Cabin'].fillna('U')

# 2. Extract the first character as the Deck letter
train_df['Cabin_Deck'] = train_df['Cabin'].str.slice(0, 1)
test_df['Cabin_Deck'] = test_df['Cabin'].str.slice(0,1)

#Check new decks and their counts in train set
print(train_df['Cabin_Deck'].value_counts())

Cabin_Deck
U    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [337]:
#Check new decks and their counts in test set
print(test_df['Cabin_Deck'].value_counts())

Cabin_Deck
U    327
C     35
B     18
D     13
E      9
F      8
A      7
G      1
Name: count, dtype: int64

In [338]:
#drop cabin feature
train_df = train_df.drop(columns=['Cabin'])
test_df = test_df.drop(columns=['Cabin'])

In [339]:
# Count how many rows share the same ticket number across your dataset
train_df['Ticket_Frequency'] = train_df['Ticket'].map(train_df['Ticket'].value_counts())
test_df['Ticket_Frequency'] =   test_df['Ticket'].map(test_df['Ticket'].value_counts())

In [340]:
#drop ticket feature
train_df = train_df.drop(columns=['Ticket'])
test_df = test_df.drop(columns=['Ticket'])

In [341]:
#Imputer that fills age missing values based on the median age of the corresponding 'Title'
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin

class TitleAgeImputerAndBinner(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.title_medians_ = {}
        self.global_median_ = 0.0

    def fit(self, X, y=None):
        # Make a copy to avoid mutating the original dataframe
        X_ = X.copy()
        
        # Calculate the median age for each title strictly from the training data
        self.title_medians_ = X_.groupby('Title')['Age'].median().to_dict()
        
        # Calculate a global fallback median
        self.global_median_ = X_['Age'].median()
        return self

    def transform(self, X):
        X_ = X.copy()
        
        # 1. Fill missing ages using the learned training medians
        for title, median_val in self.title_medians_.items():
            mask = (X_['Title'] == title) & (X_['Age'].isnull())
            X_.loc[mask, 'Age'] = median_val
            
        # 2. Fill any remaining NaNs with the global median
        X_['Age'] = X_['Age'].fillna(self.global_median_)
        
        return X_

In [355]:
#Create a family survival rate encoder that calculates family survival rate on each Fold of the K-Folds
from sklearn.base import BaseEstimator, TransformerMixin

class FamilySurvivalEncoder(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.family_survival_map = {}

    def fit(self, X, y=None):
        # Ensure we have a DataFrame and y is provided
        if y is None:
            raise ValueError("FamilySurvivalEncoder requires y during fit.")
        
        temp_df = X.copy()
        temp_df['Survived'] = y
        # Calculate mean survival per family name from training data
        self.family_survival_map = temp_df.groupby('Family_Name')['Survived'].mean().to_dict()
        return self

    def transform(self, X):
        X_out = X.copy()
        # Map the training survival rates to the current set
        X_out['Family_Survival_Rate'] = X_out['Family_Name'].map(self.family_survival_map)
        # Fill unseen/new families with a neutral baseline (0.5)
        X_out['Family_Survival_Rate'] = X_out['Family_Survival_Rate'].fillna(0.5)
        return X_out

In [373]:
#Create sub-pipelines to scale continuous-valued features and one-hot encode class-based features
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler , OneHotEncoder , OrdinalEncoder

# 1. Separate Family_Category from other categorical features
num_features = ['Pclass','Age', 'Fare', 'Ticket_Frequency' , 'Family_Survival_Rate']
ohe_cat_features = ['Sex', 'Embarked', 'Title' , 'Cabin_Deck']
ord_cat_features = ['Family_Category']

# 2. Define category ordering for Family_Category (Alone -> Small -> Large)
family_category_order = [['Alone', 'Small', 'Large']]

# 3. Create sub-pipelines
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

ohe_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

ordinal_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ordinal', OrdinalEncoder(categories=family_category_order, handle_unknown='use_encoded_value', unknown_value=-1))
])

# 4. Combine into ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, num_features),
    ('ohe_cat', ohe_transformer, ohe_cat_features),
    ('ord_cat', ordinal_transformer, ord_cat_features)
])

In [374]:
#Create the final Random Forest pipeline
from xgboost import XGBClassifier

master_pipeline = Pipeline(steps=[
    ('age_processor' , TitleAgeImputerAndBinner()),
    ('family_survival_processor' , FamilySurvivalEncoder()),
    ('preprocessor', preprocessor),
    ('model', XGBClassifier(random_state=42))
])

In [375]:
#Define x_train and y_train

X_train = train_df.drop(columns=['Survived'])
y_train = train_df['Survived']

In [372]:
#calculate cross_val_score without hyperparameter tuning
from sklearn.model_selection import cross_val_score

cvs = cross_val_score(master_pipeline , X_train , y_train , cv=10 , scoring='accuracy')
print(f'cross validation scores: {cvs}')
print(f'mean xgboost cross val score: {cvs.mean()}')

cross validation scores: [0.83333333 0.7752809  0.75280899 0.79775281 0.80898876 0.78651685
 0.74157303 0.75280899 0.79775281 0.82022472]
mean xgboost cross val score: 0.7867041198501873

mean xgboost cross val score: 0.8080848659845585  (After dropping family survival rate)

In [362]:
from sklearn.model_selection import GridSearchCV

master_pipeline.set_params(
    model=XGBClassifier(
        n_estimators=100,
        max_depth=3,
        learning_rate=0.1,
        random_state=42,
        eval_metric='logloss'
    )
)


xgb_param_grid = {
    'model__n_estimators': [50, 100, 200],
    'model__max_depth': [3, 5, 7],
    'model__learning_rate': [0.01, 0.05, 0.1, 0.2],
    'model__subsample': [0.8, 1.0]
}


# Run GridSearch
xgb_grid = GridSearchCV(
    master_pipeline, 
    xgb_param_grid, 
    cv=5, 
    scoring='accuracy', 
    n_jobs=-1
)
xgb_grid.fit(X_train, y_train)

print("Best Parameters:", xgb_grid.best_params_)
print("Best Accuracy Score:", xgb_grid.best_score_)

Best Parameters: {'model__learning_rate': 0.05, 'model__max_depth': 7, 'model__n_estimators': 100, 'model__subsample': 0.8}
Best Accuracy Score: 0.7912121021906974

Best Accuracy Score: 0.7912121021906974 (OHE Family_Category, No Cabin Deck)

Best Accuracy Score: 0.7912121021906974 (OE Family_Category , No Cabin Deck)

Best Accuracy Score: 0.7912121021906974 (OE Family_Category , No Cabin Deck , Pclass as numeric)

Best Accuracy Score: 0.8417487916640513 (OE Family_Category , No Cabin Deck , Pclass as numeric , dropped Family_survival_rate)

In [381]:
#predict for test set

#choose model with best hyperparameters
master_pipeline.set_params(**xgb_grid.best_params_)
#Fit training data into model with best hyperparameters and predict on test data
master_pipeline.fit(X_train , y_train)

Pipeline(steps=[('age_processor', TitleAgeImputerAndBinner()),
                ('family_survival_processor', FamilySurvivalEncoder()),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Pclass', 'Age', 'Fare',
                                                   'Ticket_Frequency',
                                                   'Family_Survival_Rate']),
                                                 ('ohe_cat',
                                                  Pipeline(st...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=7, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=100, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [382]:
#predict on test data
predictions = master_pipeline.predict(test_df)

In [ ]:
#generate submission csv
test_ids = pd.read_csv('test.csv')['PassengerId']
submission = pd.DataFrame({
    'PassengerId': test_ids,
    'Survived': predictions
})

submission.to_csv('submission5.csv', index=False)